sudo: required
services:
  - docker

before_install:
  - docker build -t djohal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true djohal/react-test npm test

after_success:
  - docker build -t djohal/complex-client ./client
  - docker build -t djohal/complex-server ./server
  - docker build -t djohal/complex-nginx ./nginx
  - docker build -t djohal/complex-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push djohal/complex-client
  - docker push djohal/complex-server
  - docker push djohal/complex-nginx
  - docker push djohal/complex-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-complex
  env: DockerComplex-env
  bucket_name: elasticbeanstalk-us-east-2-102763781490
  bucket_path: docker-complex
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
